// <auto-generated />
using System;
using MedicalRecordService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalRecordService.Migrations
{
    [DbContext(typeof(MedicalRecordDbContext))]
    [Migration("20260919090000_AddConsultationCompletion")]
    partial class AddConsultationCompletion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MedicalRecordService.Models.Entities.Consultation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "ascii");

                    b.Property<DateTime>("ConsultationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("DoctorId"), "ascii");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("EventId"), "ascii");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ExaminationFindings")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("PatientId"), "ascii");

                    b.Property<Guid>("QueueId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("QueueId"), "ascii");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("IN_PROGRESS");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("TemplateId"), "ascii");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationDate")
                        .HasDatabaseName("IX_Consultations_ConsultationDate");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_Consultations_DoctorId");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("UX_Consultations_EventId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Consultations_PatientId");

                    b.HasIndex("QueueId")
                        .IsUnique()
                        .HasDatabaseName("UX_Consultations_QueueId");

                    b.ToTable("Consultations", (string)null);
                });

            modelBuilder.Entity("MedicalRecordService.Models.Entities.ConsultationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "ascii");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExaminationFindings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_ConsultationTemplates_Name");

                    b.ToTable("ConsultationTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExaminationFindings = "Examination findings:\n- ",
                            IsActive = true,
                            Name = "General Consultation",
                            Notes = "Assessment and plan:\n- ",
                            Symptoms = "Presenting symptoms:\n- "
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExaminationFindings = "Respiratory examination findings:\n- ",
                            IsActive = true,
                            Name = "Respiratory Consultation",
                            Notes = "Respiratory assessment and plan:\n- ",
                            Symptoms = "Respiratory symptoms:\n- "
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExaminationFindings = "Abdominal examination findings:\n- ",
                            IsActive = true,
                            Name = "Gastrointestinal Consultation",
                            Notes = "Gastrointestinal assessment and plan:\n- ",
                            Symptoms = "Gastrointestinal symptoms:\n- "
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExaminationFindings = "Musculoskeletal examination findings:\n- ",
                            IsActive = true,
                            Name = "Musculoskeletal Consultation",
                            Notes = "Musculoskeletal assessment and plan:\n- ",
                            Symptoms = "Musculoskeletal symptoms:\n- "
                        });
                });

            modelBuilder.Entity("MedicalRecordService.Models.Entities.VitalSigns", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("Id"), "ascii");

                    b.Property<decimal?>("Bmi")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ConsultationId"), "ascii");

                    b.Property<int?>("DiastolicBloodPressure")
                        .HasColumnType("int");

                    b.Property<decimal?>("HeightCentimeters")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("OxygenSaturation")
                        .HasColumnType("int");

                    b.Property<int?>("PulseRate")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("int");

                    b.Property<int?>("SystolicBloodPressure")
                        .HasColumnType("int");

                    b.Property<decimal?>("TemperatureCelsius")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal?>("WeightKilograms")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId")
                        .IsUnique()
                        .HasDatabaseName("UX_VitalSigns_ConsultationId");

                    b.ToTable("VitalSigns", (string)null);
                });

            modelBuilder.Entity("MedicalRecordService.Models.Entities.Consultation", b =>
                {
                    b.HasOne("MedicalRecordService.Models.Entities.ConsultationTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Consultations_ConsultationTemplates_TemplateId");
                });

            modelBuilder.Entity("MedicalRecordService.Models.Entities.VitalSigns", b =>
                {
                    b.HasOne("MedicalRecordService.Models.Entities.Consultation", "Consultation")
                        .WithOne("VitalSigns")
                        .HasForeignKey("MedicalRecordService.Models.Entities.VitalSigns", "ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VitalSigns_Consultations_ConsultationId");

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("MedicalRecordService.Models.Entities.Consultation", b =>
                {
                    b.Navigation("VitalSigns");
                });
#pragma warning restore 612, 618
        }
    }
}
