// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueueService.Data;

#nullable disable

namespace QueueService.Migrations
{
    [DbContext(typeof(QueueDbContext))]
    [Migration("20260829052328_InitialQueueSchema")]
    partial class InitialQueueSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("QueueService.Models.Entities.DailyQueueCounter", b =>
                {
                    b.Property<DateOnly>("QueueDate")
                        .HasColumnType("date");

                    b.Property<int>("LastNumber")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("QueueDate");

                    b.ToTable("DailyQueueCounters");
                });

            modelBuilder.Entity("QueueService.Models.Entities.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EventId");

                    b.ToTable("ProcessedEvents");
                });

            modelBuilder.Entity("QueueService.Models.Entities.QueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("QueueDate")
                        .HasColumnType("date");

                    b.Property<string>("QueueNumber")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "QueueDate")
                        .IsUnique();

                    b.HasIndex("QueueDate", "QueueNumber")
                        .IsUnique();

                    b.ToTable("QueueEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
